const express = require('express');
const UsersModel = require('../models/Users');
const multer = require('multer');

var upload = multer({dest:'uploads/'});
var router = express.Router();


router.post('/gravetar', upload.single('gravetar'), function (req, res) {
  let file = req.file;
  if (!file) {
    res.statusMessage = 'Not found';
    return;
  }
  console.log({file});

  //make sure file is a image
  let gravatar_id = "randomly generated by bcrypt";
  let gravatar_ext = "extension of orignal file --function to find this is to be made";
  let User_id = "id of the user --to be found in the cookies"

  UsersModel.update({gravatar_id, gravatar_ext}, { where: {User_id} })
  .then(result =>
    console.log({result})
    //rename file (fs.rename) to random hash
  )
  .catch(err =>
    console.log({err})
    // res.json(err)
  )

});

module.exports = router;
